version: "2"

services:
  app:
    build: ./app
    command: flask run --host 0.0.0.0 --port 8000
    volumes:
    - ./app:/usr/local/src/jekylledit
    - ./sites:/var/www/jekylledit
    - ./data:/mnt
    ports:
    - "8000:8000"
    env_file: ./app/environment
  javascript:
    image: klokantech/plovr:5.0.1
    command: make serve
    volumes:
    - ./javascript:/data
    - ./app/jekylledit/static/js:/mnt
    ports:
    - "9810:9810"
