version: "2"

services:
  app:
    working_dir: /venv/app/jekylledit
    volumes:
      - ./data:/mnt
      - ./sites:/var/www/jekyledit
    environment:
      - SQLALCHEMY_DATABASE_URI=sqlite:////mnt/database.sqlite
